//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStoreMVCUsingLinq
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginHistory
    {
        public int PKUserLoginHistoryId { get; set; }
        public int FKUserId { get; set; }
        public System.DateTime LoginDateTime { get; set; }
        public string IPAddress { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
